### PR TITLE
More sprite sheets and unfinished gun "is_sprite_sheet" code

### PR DESCRIPTION
**Pull request by Molisson**

### CODE REVIEW

**Comment by Molisson** [comment]
I think I will expand this pull request even further, this might be interesting

**Comment by Molisson** [comment]
Ok, I think that's all I got for today, maybe tomorrow I will probably continue

**Comment by Booraz149** [comment]
I think Eric will need to check this one.

**Comment by Molisson** [comment]
I will probably continue this pull request in the future.
I'm not sure if this pull request is going to be merged, because it is not going to happen, maybe

**Comment by Molisson** [comment]
Moving this pull request to another with a few changes

**Pull request closed without merging**
