### PR TITLE
Mining Drill

### PR DESCRIPTION
**Pull request by Linkin01**
Hello Eric, I've made a mining drill(gun class) with LazyRain. I tried to balance out the stuff I think it's good enough but You can tweak it later. 
It has its own sound, animation.
It has a cooldown property.

### CODE REVIEW

**Comment by Linkin01** [comment]
https://cdn.discordapp.com/attachments/721124121630474340/826440761096405052/out.mp4
Comparison

**Comment by Eric-Gurt** [comment]
Lines like
`this.cooldown = this.cooldown - 0.015;`
better be turned into something like
`this.cooldown = this.cooldown - 0.015 / 2 * GSPEED;`
Because server-side frames (client-side too) time can vary and GSPEED would be 0.5 for 60 FPS case and 1 for 30 FPS cases.

Do you think you could test it locally to see if it works correctly after this change applied? I'd assume on my hardware it might work slightly different that on you or anyone else's.

Also tell me here if gun_drill sound is original or was taken from somewhere. I can make new one if needed.

**Comment by Linkin01** [comment]
Yeah, the sound is original. But if you have a good sfx idea then you can make your own :D I've made this really fast maybe yours can be better and can be more fitting to the game.

I've tested the code, it looks like both 60(0.5) and 30(1) ones take longer time to overheat, is there any better solution? Maybe we can make the 0.015 value higher so it can work flawlessly, for example 0.030?

**Comment by Linkin01** [comment]
I've also tried the GSPEED variable, the debugger said that it wasn't defined. It's in somewhere but I don't know.

**Comment by Eric-Gurt** [comment]
Hmm I see why.

sdGun.prototype.Shoot( background_shoot=0, offset=null ) method is only ever called when player holds fire button.

Thus this.cooldown will ever only change when attack is being done? It might not make sense as it is now.

Perhaps sdGun.prototype.onThink is where it should be? This one does have GSPEED.

sdGun.prototype.Shoot could get GSPEED for continuous and beam-like attacks but from my PB2.5/3 experience it would overcomplicate game's logic by a lot and probably won't solve current needs of gun_drill. Also SD2D does play sounds as separate event unless it handled like jetpack sounds.

**Pull request closed without merging**
