### PR TITLE
New drone enemy

### PR DESCRIPTION
**Pull request by c86ec23b-fef1-4979-b2fa-b9adc351b8cc**

### CODE REVIEW

**Comment by Booraz149** [comment]
Not sure if this drone should have chance to replace Falkok drone during Falkok invasion event.

**Comment by HastySnow** [comment]
Falkok drone must stay.

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
seperate event will probably come once faction gets more entities probably, if needed i can do it rn

**Comment by Eric-Gurt** [comment]
We should really consider standardizing entity appearance from left edges/top edges/right edges/anywhere near ground of world spawning and placement so new event like this one could be made with just 3 lines of code.

Teams probably can be same for now, though this is to change in future - worth to maybe leave in comment block at the beginning of sdDrone.js file.

As for notes for future, it will be very important to have as little as possible of these:
`this.type === 3`
`this.type === 2`
`this.type === 1`
Because indices like these are not quick to understand by other developers - it will be even less easy for whoever writes them in after month or a year (PB2 greatly suffered from it I could say, as well as other projects from other people I happened to work with). I do believe there can happen common burnout source when developer has to remember too many stuff since it is secretly quite exhausting.

Solution:
Define enumeration-like properties at class initialization ( static init_class() ) like this;
`static init_clas()
{
...
sdDrone.TYPE_FALKOK = 1;
sdDrone.TYPE_ERTHAL = 2;
sdDrone.TYPE_SARRORNIAN = 3;
...
}`

Currently sdDrone class doesn't have this but it will make sense to slowly shift towards that, even if it will be kind of fine to leave indices where they already used if whoever works on code does not have time to switch yet.

Also, in almost any IDE you could type "sdDrone.TYPE_" and press "Ctrl + Space" - then you can even see list of options. Works in Netbeans at very least, but it is common code hinting thing.

**Comment by Eric-Gurt** [comment]
Tell if you will do any more changes. If not - I think it is fine as is and can be merged.

**Comment by c86ec23b-fef1-4979-b2fa-b9adc351b8cc** [comment]
i think its alright now, can merge if you want

**Pull request merged**
